name: CI

on:
  push        
            
jobs:
  lint-and-test:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - uses: subosito/flutter-action@v2
            with:
              channel: 'stable'
          - name: Restore dependencies
            run: flutter pub get
          - name: Run linter
            run: flutter analyze
          - name: Run tests
            run: flutter test